### ISSUE TITLE
MetricsSource: if a new job is submitted, PeBean.retrieveMetrics fails

### ISSUE THREAD

**Issue by m-kotowski** [IBMStreams/streamsx.metrics#27]
If the test application is running, and a new job is submitted (in this case, the same test app), PeBean.retrieveMetrics raises a NullPointerException. 

```
ERROR #splapptrc,J[0],P[0],ChangeNotifications M[MetricsSource.java:com.ibm.streamsx.metrics.MetricsSource$1.run:357]  - Operator error
ERROR #splapptrc,J[0],P[0],ChangeNotifications M[?:?:0]  - java.lang.NullPointerException
ERROR #splapptrc,J[0],P[0],ChangeNotifications M[?:?:0]  - 	at com.ibm.streams.instance.srm.client.BaseMetrics.getTimestamp(BaseMetrics.java:340)
ERROR #splapptrc,J[0],P[0],ChangeNotifications M[?:?:0]  - 	at com.ibm.streams.instance.srm.client.BaseMetrics.<init>(BaseMetrics.java:192)
ERROR #splapptrc,J[0],P[0],ChangeNotifications M[?:?:0]  - 	at com.ibm.streams.instance.srm.client.PEMetrics.<init>(PEMetrics.java:64)
ERROR #splapptrc,J[0],P[0],ChangeNotifications M[?:?:0]  - 	at com.ibm.streams.instance.srm.client.SrmClient.getPEMetrics(SrmClient.java:292)
ERROR #splapptrc,J[0],P[0],ChangeNotifications M[?:?:0]  - 	at com.ibm.streams.management.internal.PeBean.retrieveMetrics(PeBean.java:952)
```

Not sure whether this is important but just before the exception is raised, 4 time the following notification is received.

```
ERROR #splapptrc,J[0],P[0],Numbers M[PeHandler.java:com.ibm.streamsx.metrics.internal.PeHandler.handleNotification:114]  - notification: javax.management.Notification[source=com.ibm.streams.management:type=domain.instance.pe,domain="domain4.2.0.0",instance="streams4.2.0.0",id=1][type=com.ibm.streams.management.pe.changed][message=], userData=null
```

**Comment by m-kotowski** [comment]
This problem is solved with IBM Streams 4.2.0.2 fixpack.
